Signing locally the transactions
nevermined-io/faucet pull request #8
Opened 2021-01-19 10:05 UTC by jcortejoso

## Description
Signing locally the transactions

2021-01-19 10:11 UTC, aaitor requested changes

2021-01-19 10:11 UTC, aaitor commented on src/controllers/neverminedFaucet.js
> +        logger.info(`SignedData: ${JSON.stringify(signedData, null, 2)}`)
logger.debug?

2021-01-19 10:11 UTC, aaitor commented on src/controllers/neverminedFaucet.js
> +                console.log('*** Transaction Confirmed ***')
logger.debug

2021-01-19 10:11 UTC, aaitor commented on src/controllers/neverminedFaucet.js
> +            .on("error", console.error)
logger.error

2021-01-20 07:56 UTC, aaitor approved these changes

2021-01-20 11:28 UTC, eruizgar91 approved these changes
:rocket:

2021-01-20 11:35 UTC, H34D approved these changes
LGTM

2021-01-20 11:37 UTC, merged